[[repos]]
repo = "local"
hooks = [
    {
        id = "cargo-fmt",
        name = "Cargo fmt",
        language = "system",
        entry = "cargo fmt --check",
        always_run = true,
        pass_filenames = false,
    },
    {
        id = "cargo-clippy",
        name = "Cargo clippy",
        language = "system",
        entry = "cargo clippy --all-targets --all-features -- -D warnings",
        always_run = true,
        pass_filenames = false,
    },
    {
        id = "cargo-check",
        name = "Cargo check",
        language = "system",
        entry = "cargo check",
        always_run = true,
        pass_filenames = false,
    },
]
